#ifndef spotiqueue_worker_h
#define spotiqueue_worker_h

/* WARNING: This file is auto-generated by cbindgen. Don't modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void set_callback(void (*callback)(int32_t i));

bool spotiqueue_initialize_worker(const char *username_raw, const char *password_raw);

bool spotiqueue_pause_playback(void);

bool spotiqueue_play_track(const char *spotify_uri_raw);

#endif /* spotiqueue_worker_h */
