#ifndef spotiqueue_worker_h
#define spotiqueue_worker_h

/* WARNING: This file is auto-generated by cbindgen. Don't modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

bool spotiqueue_initialize_worker(const char *username_raw, const char *password_raw);

#endif /* spotiqueue_worker_h */
